### PR TITLE
Add GHA to add wheel to release

### PR DESCRIPTION
**Pull request by mmacata**
With this PR, after a release a python wheel is build from the released code and added to the release itself.

### CODE REVIEW

**Review by marcjansen — APPROVED** [review]
Great, thx

**Comment by marcjansen** [comment]
Hmm: 

```
| ❌ YAML        | yamllint                 | list_of_files |     4 |       |      1 |        0.15s |
```

**Comment by mmacata** [comment]
> Hmm:
> 
> ```
> | ❌ YAML        | yamllint                 | list_of_files |     4 |       |      1 |        0.15s |
> ```

Only because @joaherrerama added the most powerfull linter in all our repos :D 
I will look into it.

**Comment by joaherrerama** [comment]
I think the error is just because it is a good practice to start YAML files with `---` :D

**Review by joaherrerama — APPROVED** [review]
Nice, thanks

**Comment by mmacata** [comment]
> I think the error is just because it is a good practice to start YAML files with `---` :D

:D but this was just a warning. I fixed the error, it was `Error: [indentation] wrong indentation: expected 6 but found 4
457`

**Pull request merged**
